### ISSUE TITLE
Bug Worker

### ISSUE THREAD

**Issue by Leoche** [Leoche/IdleNuts#2]
J'ai update pour mettre un loop de jeu simple pour update les workers toutes les 30ms mais les workers ont de base une calculateTotalProduction() = 1 Même si on a aucun squirrel

jcrois t'as du te mélanger entre this.base et this.lvl enfin jsp
@esunea

**Comment by Leoche** [comment]
Essaye de remplacer dans Worker.js depuis https://github.com/Leoche/IdleNuts/commit/059a1efc7e4096879027280b605d2c849853e8ee
`  calculateTotalProduction() {
    return this.base * this.ratio;
  }`
par 
`  calculateTotalProduction() {
    return this.lvl * this.ratio;
  }`
Là ça marche mais ça s'incremente trop vite

**Comment by esunea** [comment]
ouais j'ai vu j'vais essayer de fix ça
